# Generated by Django 3.2.18 on 2023-04-22 21:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timpestamp', models.CharField(max_length=100)),
                ('temperature', models.CharField(max_length=100, null=True)),
                ('humidity', models.CharField(max_length=100, null=True)),
                ('water_level', models.CharField(max_length=100, null=True)),
                ('hour', models.CharField(max_length=100, null=True)),
                ('minutes', models.CharField(max_length=100, null=True)),
                ('seconds', models.CharField(max_length=100, null=True)),
                ('django_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
