# Generated by Django 3.2.18 on 2023-04-22 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensordata',
            old_name='timpestamp',
            new_name='timestamp',
        ),
    ]
